import { PageLayout } from '@/components/layout/page-layout';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { CheckCircle, Building2, ArrowRight, LogIn, Crown, TrendingUp } from 'lucide-react';
import SampleOutputsGrid from '@/components/sample-outputs-grid';
import { cn } from '@/lib/utils';
import { generatePageMetadata, industryMetadata } from '@/lib/metadata';

export const metadata = generatePageMetadata({
  ...industryMetadata.beauty,
  path: "/beauty-personal-care"
});

export default function BeautyPersonalCarePage() {
  const benefits = [
    "Luxury product photos with soft lighting and refined reflections",
    "Models naturally applying products, showcasing usage effectiveness",
    "High-aesthetic beauty campaign content for social media",
    "Authentic UGC content resembling real customer reviews"
  ];

  const beautyCategories = [
    { name: "Skincare", examples: "Serums, moisturizers, face masks" },
    { name: "Makeup", examples: "Lipstick, eyeshadow, foundation" },
    { name: "Haircare", examples: "Shampoo, conditioner, styling" },
    { name: "Fragrance", examples: "Perfume, body mist, cologne" }
  ];

  const pricingHighlight = [
    { plan: "Starter", price: "99k", images: "10 products", best: false },
    { plan: "Pro", price: "528k", images: "41 products", best: true },
    { plan: "Business", price: "1.58M", images: "125 products", best: false }
  ];

  const beforeAfter = [
    { aspect: "Photo shoot cost", before: "$200-$600", after: "12k VND", saving: "99.9%" },
    { aspect: "Time", before: "3-5 days", after: "30 seconds", saving: "99.8%" },
    { aspect: "Number of images", before: "5-8 images", after: "12 images", saving: "+50%" },
    { aspect: "Quality", before: "Inconsistent", after: "Consistent", saving: "100%" }
  ];

  return (
    <PageLayout
      title="AI-Powered Beauty & Personal Care Images"
      subtitle="Specialized prompts for cosmetics — Luxury aesthetic, model application, skincare campaigns"
    >
      <div className="space-y-16">
        {/* Hero Benefits */}
        <div className="bg-gradient-to-r from-pink-50 to-purple-50 rounded-2xl p-8 border border-pink-100">
          <div className="text-center mb-8">
            <div className="w-20 h-20 bg-gradient-to-br from-pink-500 to-purple-500 rounded-2xl mx-auto mb-6 flex items-center justify-center shadow-lg">
              <Building2 className="w-10 h-10 text-white" />
            </div>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              AI Specialized for Beauty & Personal Care
            </h2>
            <p className="text-xl text-gray-600">
              Prompts optimized for luxury aesthetic, skin glow, and beauty application
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {benefits.map((benefit, index) => (
              <div key={index} className="flex items-start gap-3">
                <CheckCircle className="w-5 h-5 text-pink-500 mt-1 flex-shrink-0" />
                <p className="text-gray-700">{benefit}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Beauty Categories */}
        <div>
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
            Perfect for Every Beauty Product
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {beautyCategories.map((category, index) => (
              <Card key={index} className="border-pink-200 hover:shadow-lg transition-shadow">
                <CardContent className="p-6 text-center">
                  <div className="w-12 h-12 bg-pink-100 rounded-xl mx-auto mb-4 flex items-center justify-center">
                    <Building2 className="w-6 h-6 text-pink-600" />
                  </div>
                  <h3 className="font-bold text-gray-900 mb-2">{category.name}</h3>
                  <p className="text-gray-600 text-sm">{category.examples}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Sample Outputs */}
        <div>
          <SampleOutputsGrid
            title="Sample Beauty Images Generated by SnapStudio"
            subtitle="Luxury display • Model application • Beauty campaigns • UGC reviews"
          />
        </div>

        {/* Comparison Table */}
        <div className="bg-white rounded-2xl p-8 shadow-lg border border-gray-200">
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
            Comparison: Studio vs SnapStudio AI
          </h2>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="bg-gradient-to-r from-pink-500 to-purple-500 text-white">
                  <th className="p-4 text-left rounded-tl-lg">Criteria</th>
                  <th className="p-4 text-left">Traditional Studio</th>
                  <th className="p-4 text-left">SnapStudio AI</th>
                  <th className="p-4 text-left rounded-tr-lg">Savings</th>
                </tr>
              </thead>
              <tbody>
                {beforeAfter.map((row, index) => (
                  <tr key={index} className={index % 2 === 0 ? 'bg-pink-50' : 'bg-white'}>
                    <td className="p-4 font-medium text-gray-900">{row.aspect}</td>
                    <td className="p-4 text-gray-600">{row.before}</td>
                    <td className="p-4 text-pink-600 font-semibold">{row.after}</td>
                    <td className="p-4 text-green-600 font-bold">{row.saving}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Clean Pricing */}
        <div className="bg-gradient-to-r from-pink-50 to-purple-50 rounded-2xl p-8 border border-pink-100">
          <div className="text-center mb-8">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Pricing for Beauty Brands
            </h2>
            <p className="text-lg text-gray-600">
              Based on number of cosmetic products per month
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            {pricingHighlight.map((plan, index) => (
              <Card key={index} className={cn(
                "border-2 transition-all hover:scale-105",
                plan.best ? "border-pink-500 shadow-lg" : "border-gray-200"
              )}>
                <CardContent className="p-6 text-center">
                  {plan.best && (
                    <Badge className="bg-pink-500 text-white mb-4">
                      POPULAR
                    </Badge>
                  )}
                  <h3 className="text-xl font-bold text-gray-900 mb-2">{plan.plan}</h3>
                  <div className="text-2xl font-bold text-pink-600 mb-2">{plan.price}</div>
                  <p className="text-gray-600 mb-4">{plan.images}</p>
                  <Button 
                    className={cn(
                      "w-full auth-trigger",
                      plan.best 
                        ? "bg-pink-500 hover:bg-pink-600" 
                        : "bg-gray-900 hover:bg-gray-800"
                    )}
                  >
                    Choose {plan.plan}
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
          
          <div className="text-center">
            <p className="text-gray-600 mb-6">
              <strong>Per product</strong> = 12 images (Studio luxury, Model application, Social campaign, UGC review)
            </p>
            <Button size="lg" className="bg-gradient-to-r from-pink-500 to-purple-500 hover:from-pink-600 hover:to-purple-600 text-white auth-trigger">
              <Crown className="w-5 h-5 mr-2" />
              Start Creating Beauty Images
              <ArrowRight className="w-5 h-5 ml-2" />
            </Button>
          </div>
        </div>

        {/* Success Stories */}
        <div>
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
            Beauty Brands Succeeding with SnapStudio
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <Card className="border-pink-200">
              <CardContent className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 bg-pink-100 rounded-xl flex items-center justify-center">
                    <Building2 className="w-6 h-6 text-pink-600" />
                  </div>
                  <div>
                    <h3 className="font-bold text-gray-900">Skincare Brand X</h3>
                    <p className="text-sm text-gray-600">Cosmetics startup</p>
                  </div>
                </div>
                <p className="text-gray-700 mb-4">
                  "Since using SnapStudio, we've saved 90% of our photo shoot budget.
                  Conversion rate increased 180% thanks to beautiful, consistent images."
                </p>
                <div className="flex gap-2">
                  <Badge className="bg-green-100 text-green-700">+180% conversion</Badge>
                  <Badge className="bg-blue-100 text-blue-700">-90% cost</Badge>
                </div>
              </CardContent>
            </Card>

            <Card className="border-purple-200">
              <CardContent className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center">
                    <Building2 className="w-6 h-6 text-purple-600" />
                  </div>
                  <div>
                    <h3 className="font-bold text-gray-900">Makeup Brand Y</h3>
                    <p className="text-sm text-gray-600">Makeup brand</p>
                  </div>
                </div>
                <p className="text-gray-700 mb-4">
                  "12 images per product with enough styles for every platform.
                  Content calendar never runs out of beautiful photos!"
                </p>
                <div className="flex gap-2">
                  <Badge className="bg-purple-100 text-purple-700">12 styles</Badge>
                  <Badge className="bg-orange-100 text-orange-700">All platforms</Badge>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </PageLayout>
  );
}