import { PageLayout } from '@/components/layout/page-layout';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { CheckCircle, Building2, ArrowRight, LogIn, TrendingUp } from 'lucide-react';
import SampleOutputsGrid from '@/components/sample-outputs-grid';
import { cn } from '@/lib/utils';
import { generatePageMetadata, industryMetadata } from '@/lib/metadata';

export const metadata = generatePageMetadata({
  ...industryMetadata.f_b,
  path: "/food-beverage"
});

export default function FoodBeveragePage() {
  const benefits = [
    "Studio food photos with even lighting and fresh, appetizing colors",
    "Models naturally enjoying the food, increasing cravings",
    "Eye-catching social media content for every platform",
    "Authentic UGC content resembling real customer reviews"
  ];

  const useCases = [
    { title: "Restaurants & Cafes", description: "Digital menus, posters, social media" },
    { title: "Food Delivery", description: "Food photos for delivery apps" },
    { title: "F&B Brands", description: "Marketing campaigns, packaging" },
    { title: "Food Content", description: "Blog, review, recipe posts" }
  ];

  const pricingHighlight = [
    { plan: "Starter", price: "99k", images: "10 dishes", best: false },
    { plan: "Pro", price: "528k", images: "41 dishes", best: true },
    { plan: "Business", price: "1.58M", images: "125 dishes", best: false }
  ];

  return (
    <PageLayout
      title="AI-Powered Food & Beverage Images"
      subtitle="Specialized prompts for F&B — Studio shots, lifestyle dining, social content"
    >
      <div className="space-y-16">
        {/* Hero Benefits */}
        <div className="bg-gradient-to-r from-orange-50 to-red-50 rounded-2xl p-8 border border-orange-100">
          <div className="text-center mb-8">
            <div className="w-20 h-20 bg-gradient-to-br from-orange-500 to-red-500 rounded-2xl mx-auto mb-6 flex items-center justify-center shadow-lg">
              <Building2 className="w-10 h-10 text-white" />
            </div>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              AI Specialized for Food & Beverage
            </h2>
            <p className="text-xl text-gray-600">
              Prompts optimized for freshness, plating, and food styling
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {benefits.map((benefit, index) => (
              <div key={index} className="flex items-start gap-3">
                <CheckCircle className="w-5 h-5 text-orange-500 mt-1 flex-shrink-0" />
                <p className="text-gray-700">{benefit}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Use Cases */}
        <div>
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
            Perfect for Every Type of F&B Business
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {useCases.map((useCase, index) => (
              <Card key={index} className="border-orange-200 hover:shadow-lg transition-shadow">
                <CardContent className="p-6 text-center">
                  <h3 className="text-lg font-bold text-gray-900 mb-2">{useCase.title}</h3>
                  <p className="text-gray-600 text-sm">{useCase.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Sample Outputs */}
        <div>
          <SampleOutputsGrid
            title="Sample F&B Images Generated by SnapStudio"
            subtitle="Studio shots • Lifestyle dining • Social posts • UGC content"
          />
        </div>

        {/* Clean Pricing */}
        <div className="bg-gradient-to-r from-orange-50 to-yellow-50 rounded-2xl p-8 border border-orange-100">
          <div className="text-center mb-8">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Pricing for F&B
            </h2>
            <p className="text-lg text-gray-600">
              Based on number of dishes to photograph per month
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            {pricingHighlight.map((plan, index) => (
              <Card key={index} className={cn(
                "border-2 transition-all hover:scale-105",
                plan.best ? "border-orange-500 shadow-lg" : "border-gray-200"
              )}>
                <CardContent className="p-6 text-center">
                  {plan.best && (
                    <Badge className="bg-orange-500 text-white mb-4">
                      POPULAR
                    </Badge>
                  )}
                  <h3 className="text-xl font-bold text-gray-900 mb-2">{plan.plan}</h3>
                  <div className="text-2xl font-bold text-orange-600 mb-2">{plan.price}</div>
                  <p className="text-gray-600 mb-4">{plan.images}</p>
                  <Button 
                    className={cn(
                      "w-full auth-trigger",
                      plan.best 
                        ? "bg-orange-500 hover:bg-orange-600" 
                        : "bg-gray-900 hover:bg-gray-800"
                    )}
                  >
                    Choose {plan.plan}
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
          
          <div className="text-center">
            <p className="text-gray-600 mb-6">
              <strong>Per dish</strong> = 12 multi-style images (Display, Model, Social, Seeding)
            </p>
            <Button size="lg" className="bg-gradient-to-r from-orange-500 to-red-500 hover:from-orange-600 hover:to-red-600 text-white auth-trigger">
              <LogIn className="w-5 h-5 mr-2" />
              Start Creating F&B Images
              <ArrowRight className="w-5 h-5 ml-2" />
            </Button>
          </div>
        </div>

        {/* ROI Comparison */}
        <div className="bg-white rounded-2xl p-8 shadow-lg border border-gray-200">
          <h2 className="text-2xl font-bold text-gray-900 mb-6 text-center">
            F&B Cost Comparison
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
                <div className="w-4 h-4 bg-gray-400 rounded"></div>
                Traditional Studio
              </h3>
              <ul className="space-y-2 text-gray-600">
                <li>• Cost: $80-$200/session</li>
                <li>• Time: 1-2 days</li>
                <li>• Result: 5-8 images/dish</li>
                <li>• <strong>Total: 3-7 days, $80-$200</strong></li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-orange-600 mb-4 flex items-center gap-2">
                <div className="w-4 h-4 bg-orange-500 rounded"></div>
                SnapStudio
              </h3>
              <ul className="space-y-2 text-gray-700">
                <li>• Cost: 120 credits (~$0.50)</li>
                <li>• Time: 30 seconds</li>
                <li>• Result: 12 images/dish (4 styles)</li>
                <li>• <strong className="text-green-600">Total: 30 seconds, ~$0.50</strong></li>
              </ul>
            </div>
          </div>
          <div className="text-center mt-8 p-6 bg-green-50 rounded-xl border border-green-200">
            <div className="flex items-center justify-center gap-2 mb-2">
              <TrendingUp className="w-6 h-6 text-green-600" />
              <p className="text-xl font-bold text-green-600">
                Save 99.8% on time and 99.5% on cost!
              </p>
            </div>
          </div>
        </div>
      </div>
    </PageLayout>
  );
}