import { PageLayout } from '@/components/layout/page-layout';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { CheckCircle, Heart, Shield, ArrowRight, LogIn, Building2 } from 'lucide-react';
import SampleOutputsGrid from '@/components/sample-outputs-grid';
import { cn } from '@/lib/utils';
import { generatePageMetadata, industryMetadata } from '@/lib/metadata';

export const metadata = generatePageMetadata({
  ...industryMetadata.mother_baby,
  path: "/mother-baby"
});

export default function MotherBabyPage() {
  const benefits = [
    "Safe baby product photos with soft lighting and pastel colors",
    "Warm family moments with parents and children",
    "Family-friendly social content with a cozy tone",
    "Authentic UGC content resembling real parent reviews"
  ];

  const babyCategories = [
    { name: "Baby Care", examples: "Diapers, baby wash, moisturizer" },
    { name: "Feeding", examples: "Bottles, spoons, high chairs" },
    { name: "Toys & Play", examples: "Toys, books, strollers" },
    { name: "Mom Care", examples: "Prenatal and postpartum products" }
  ];

  const safetyFeatures = [
    { feature: "Soft Lighting", description: "Gentle, non-harsh lighting perfect for baby products" },
    { feature: "Pastel Colors", description: "Soft colors that create a sense of safety" },
    { feature: "Family Context", description: "Family settings that emphasize warmth and love" },
    { feature: "Trust Building", description: "Increases parent confidence in the product" }
  ];

  return (
    <PageLayout
      title="AI-Powered Mother & Baby Images"
      subtitle="Specialized prompts for baby products — Safe, warm, family-friendly"
    >
      <div className="space-y-16">
        {/* Hero Benefits */}
        <div className="bg-gradient-to-r from-blue-50 to-cyan-50 rounded-2xl p-8 border border-blue-100">
          <div className="text-center mb-8">
            <div className="w-20 h-20 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-2xl mx-auto mb-6 flex items-center justify-center shadow-lg">
              <Building2 className="w-10 h-10 text-white" />
            </div>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              AI Specialized for Mother & Baby
            </h2>
            <p className="text-xl text-gray-600">
              Prompts optimized for safety, warmth, and family-friendly aesthetic
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {benefits.map((benefit, index) => (
              <div key={index} className="flex items-start gap-3">
                <CheckCircle className="w-5 h-5 text-blue-500 mt-1 flex-shrink-0" />
                <p className="text-gray-700">{benefit}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Baby Categories */}
        <div>
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
            Perfect for Every Mother & Baby Product
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {babyCategories.map((category, index) => (
              <Card key={index} className="border-blue-200 hover:shadow-lg transition-shadow">
                <CardContent className="p-6 text-center">
                  <div className="w-12 h-12 bg-blue-100 rounded-xl mx-auto mb-4 flex items-center justify-center">
                    <Building2 className="w-6 h-6 text-blue-600" />
                  </div>
                  <h3 className="font-bold text-gray-900 mb-2">{category.name}</h3>
                  <p className="text-gray-600 text-sm">{category.examples}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Safety Features */}
        <div>
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
            Safety Features for Baby Products
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {safetyFeatures.map((item, index) => (
              <Card key={index} className="border-blue-200">
                <CardContent className="p-6">
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-10 h-10 bg-blue-100 rounded-xl flex items-center justify-center">
                      <Shield className="w-5 h-5 text-blue-600" />
                    </div>
                    <h3 className="text-lg font-bold text-gray-900">{item.feature}</h3>
                  </div>
                  <p className="text-gray-600">{item.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Sample Outputs */}
        <div>
          <SampleOutputsGrid
            title="Sample Mother & Baby Images Generated by SnapStudio"
            subtitle="Safe product display • Family moments • Nursery lifestyle • Parent reviews"
          />
        </div>

        {/* Trust Building */}
        <div className="bg-white rounded-2xl p-8 shadow-lg border border-gray-200">
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
            Building Trust with Parents
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 bg-blue-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <Shield className="w-8 h-8 text-blue-600" />
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">Absolute Safety</h3>
              <p className="text-gray-600">
                Prompts emphasize product safety and quality
              </p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 bg-pink-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <Heart className="w-8 h-8 text-pink-600" />
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">Family Love</h3>
              <p className="text-gray-600">
                Warm moments that increase emotional connection
              </p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 bg-green-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <Building2 className="w-8 h-8 text-green-600" />
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">Age-Appropriate</h3>
              <p className="text-gray-600">
                Content tailored to each baby age group
              </p>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div className="text-center bg-gradient-to-r from-blue-500 to-cyan-500 text-white rounded-2xl p-12">
          <h2 className="text-4xl font-bold mb-4">
            Ready to create professional Baby images?
          </h2>
          <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
            Get started with safe, family-friendly prompts for baby products.
          </p>
          <Button 
            size="lg" 
            className="bg-white text-blue-600 hover:bg-gray-100 px-8 py-4 rounded-xl font-semibold text-lg shadow-2xl auth-trigger"
          >
            <Heart className="w-5 h-5 mr-2" />
            Start Creating Baby Images
            <ArrowRight className="w-5 h-5 ml-2" />
          </Button>
        </div>
      </div>
    </PageLayout>
  );
}